src/Brewsy.Web/Controllers/BeersController.cs
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Brewsy.Data;
using Brewsy.Domain.Entities;
using Brewsy.Web.ViewModels.Sell;
using Microsoft.AspNet.Authorization;

namespace Brewsy.Web.Controllers
{
    [Authorize]
    public class BeersController : Controller
    {
        private BrewsyContext _context;

        public BeersController(BrewsyContext context)
        {
            _context = context;    
        }

        // GET: Beers
        public IActionResult Index()
        {
            var model = new SellIndexVm();
            var user = _context.Users.FirstOrDefault(x => x.Id == User.GetUserId());

            if (!string.IsNullOrEmpty(user.StripeUserId))
            {
                model.HasStripeAccount = true;
                model.Beers = _context.Beers.Include(x => x.User).Where(x => x.UserId == User.GetUserId()).ToList();
            }

            return View(model);
        }

        // GET: Beers/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Beer beer = _context.Beers.Single(m => m.Id == id);
            if (beer == null)
            {
                return HttpNotFound();
            }

            return View(beer);
        }

        // GET: Beers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Beer beer)
        {
            beer.UserId = User.GetUserId();

            if (ModelState.IsValid)
            {
                _context.Beers.Add(beer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(beer);
        }

        // GET: Beers/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Beer beer = _context.Beers.Single(m => m.Id == id);
            if (beer == null)
            {
                return HttpNotFound();
            }

            return View(beer);
        }

        // POST: Beers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Beer beer)
        {
            if (ModelState.IsValid)
            {
                _context.Update(beer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(beer);
        }

        // GET: Beers/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Beer beer = _context.Beers.Single(m => m.Id == id);
            if (beer == null)
            {
                return HttpNotFound();
            }

            return View(beer);
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Beer beer = _context.Beers.Single(m => m.Id == id);
            _context.Beers.Remove(beer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Brewsy.Web/Controllers/PurchasesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Brewsy.Data;
using Brewsy.Domain.Entities;

namespace Brewsy.Web.Controllers
{
    public class PurchasesController : Controller
    {
        private BrewsyContext _context;

        public PurchasesController(BrewsyContext context)
        {
            _context = context;    
        }

        // GET: Purchases
        public IActionResult Index()
        {
            return View(_context.Purchases.ToList());
        }

        // GET: Purchases/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Purchase purchase = _context.Purchases.Single(m => m.Id == id);
            if (purchase == null)
            {
                return HttpNotFound();
            }

            return View(purchase);
        }

        // GET: Purchases/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Purchases/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                _context.Purchases.Add(purchase);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(purchase);
        }

        // GET: Purchases/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Purchase purchase = _context.Purchases.Single(m => m.Id == id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // POST: Purchases/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                _context.Update(purchase);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(purchase);
        }

        // GET: Purchases/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Purchase purchase = _context.Purchases.Single(m => m.Id == id);
            if (purchase == null)
            {
                return HttpNotFound();
            }

            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Purchase purchase = _context.Purchases.Single(m => m.Id == id);
            _context.Purchases.Remove(purchase);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Brewsy.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Brewsy.Web</title>

    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet"/>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet"/>
    <link href="~/css/site.min.css" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/">
                <i class="fa fa-beer"></i>
                Brewsy
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="@Url.Action("Index", "Beers")">Sell</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Purchases")">Purchases</a>
                </li>
            </ul>
            @if (!User.IsSignedIn())
            {
                <form action="@Url.Action("Login", "Account", new {ReturnUrl = @ViewData["ReturnUrl"]})" method="post" class="navbar-form navbar-right" role="form">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <input type="text" placeholder="Email" class="form-control" name="Email">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" class="form-control" name="Password">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>
            }
            else
            {
                <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a asp-controller="Manage" asp-action="Index" title="Manage">Logged in as @User.GetUserName()</a>
                        </li>
                        <li>
                            <button type="submit" class="btn btn-link navbar-btn navbar-link">Log off</button>
                        </li>
                    </ul>
                </form>
            }
        </div><!--/.navbar-collapse -->
    </div>
</nav>

<div class="body-content">
    @RenderBody()
</div>

<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">Made with <i class="fa fa-heart"></i> by <a href="http://bencull.com">Ben Cull</a>.</span>
    </div>
</footer>


<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
            
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("scripts", required: false)
</body>
</html>