src/Brewsy.Web/Controllers/ChargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Brewsy.Data;
using Brewsy.Domain.Models;
using Brewsy.Domain.Services;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Brewsy.Web.Controllers
{
    public class ChargeController : Controller
    {
        private readonly IChargeService _chargeService;
        private readonly BrewsyContext _context;

        public ChargeController(IChargeService chargeService, BrewsyContext context)
        {
            _chargeService = chargeService;
            _context = context;
        }

        [HttpPost]
        public IActionResult Index(CheckoutForm model)
        {
            var beer = _context.Beers.Include(x => x.User).FirstOrDefault(x => x.Id == model.BeerId);

            var purchase = _chargeService.Charge(model, beer);

            return RedirectToAction("Thankyou", "Home");
        }
    }
}

src/Brewsy.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Brewsy.Data;
using Brewsy.Web.ViewModels.Sell;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;

namespace Brewsy.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly BrewsyContext _context;

        public HomeController(BrewsyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new HomeIndexVm();

            model.Beers = _context.Beers.Include(x => x.User).Where(x => x.User != null).ToList();

            return View(model);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Thankyou()
        {
            return View();
        }
    }
}

src/Brewsy.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Brewsy.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Brewsy.Web/Views/Home/Index.cshtml
@model Brewsy.Web.ViewModels.Sell.HomeIndexVm
@{
    ViewData["Title"] = "Home Page";
}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Like Etsy, but beer!</h1>
        <p>Buy and Sell your homebrewed beer. Each package comes with a 6-pack of beer and a recipe so you can brew it yourself!</p>
        <p><a class="btn btn-primary btn-lg" href="@Url.Action("Register", "Account")" role="button">Become a seller</a></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        @foreach (var beer in Model.Beers)
        {
            <div class="col-md-3">
                <div class="thumbnail-beer">
                    <img src="@beer.ImageUrl" class="img-responsive"/>
                    <h4>@beer.Name</h4>
                    <p>@beer.Description</p>
                    <p>
                        <form action="@Url.Action("Index", "Charge")" method="POST">
                            <input type="hidden" name="BeerId" value="@beer.Id" />
                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="@beer.User.StripePublishableKey"
                                    data-image="@beer.ImageUrl"
                                    data-name="Brewsy"
                                    data-description="@beer.Name"
                                    data-currency="aud"
                                    data-amount="@(beer.Price*100)"
                                    data-label="Buy Now for @beer.Price.ToString("C")"
                                    data-locale="auto">
                            
                            </script>
                        </form>
                        @*<a class="btn btn-primary btn-block" href="#" role="button">Buy Now $24.99</a>*@
                    </p>
                </div>
            </div>
        }
    </div>
</div> <!-- /container -->

src/Brewsy.Web/Views/Home/Thankyou.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <h2>Thank you!</h2>
    <p>Your purchase was successful.</p>
</div>